### ISSUE TITLE
packages_modules_Connectivity repository

### ISSUE THREAD

**Issue by lingchenma** [PixelOS-Pixelish/manifest#12]
[custom.xml](https://github.com/PixelOS-AOSP/manifest/blob/fourteen/snippets/custom.xml)

There seems to be no thirteen branch under the packages_modules_Connectivity repository

**Comment by hridaya2004** [comment]
This is the repository you are looking for then, if you're looking for thirteen branch that is.

https://github.com/PixelOS-AOSP/packages_modules_Connectivity-old
