### ISSUE TITLE
fatal: unable to access 'https://gitlab.pixelexperience.org/android/external_faceunlock/': Could not resolve host: gitlab.pixelexperience.org

### ISSUE THREAD

**Issue by realdeveloperongithub** [PixelOS-Pixelish/manifest#16]
I'm trying to build for PixelOS 12.
so my repo was initialized with:
`repo init -u https://github.com/PixelOS-AOSP/manifest.git -b twelve --git-lfs`
But when i do repo sync, it tells me:

> fatal: unable to access 'https://gitlab.pixelexperience.org/android/external_faceunlock/': Could not resolve host: gitlab.pixelexperience.org
> 
> external_faceunlock:
> fatal: unable to access 'https://gitlab.pixelexperience.org/android/external_faceunlock/': Could not resolve host: gitlab.pixelexperience.org
> external_faceunlock: sleeping 4.0 seconds before retrying
> fatal: unable to access 'https://gitlab.pixelexperience.org/android/external_faceunlock/': Could not resolve host: gitlab.pixelexperience.org
> error: Cannot fetch external_faceunlock from https://gitlab.pixelexperience.org/android/external_faceunlock

I know that it is because PixelExperience is not working anymore. But is there a way to solve it?

**Comment by hridaya2004** [comment]
We no longer maintain twelve branch.
