### ISSUE TITLE
-b Thirteen Edit and Include Active Branch in Manifest for Packages_modules_connectivity.

### ISSUE THREAD

**Issue by IamAzmathullaShaikh** [PixelOS-Pixelish/manifest#17]
fatal: couldn't find remote ref refs/heads/thirteen

packages_modules_Connectivity:
fatal: couldn't find remote ref refs/heads/thirteen
packages_modules_Connectivity: sleeping 4.0 seconds before retrying
fatal: couldn't find remote ref refs/heads/thirteen
error: Cannot fetch packages_modules_Connectivity from https://github.com/PixelOS-AOSP/packages_modules_Connectivity
![Screenshot 2024-06-25 170926](https://github.com/PixelOS-AOSP/manifest/assets/107968141/13449135-ae12-4e8f-9edf-c5affbb4a208)

**Comment by hridaya2004** [comment]
We no longer maintain thirteen branch.
