### ISSUE TITLE
We no longer maintain thirteen branch.

### ISSUE THREAD

**Issue by IamAzmathullaShaikh** [PixelOS-Pixelish/manifest#18]
We no longer maintain thirteen branch.

_Originally posted by @kawaaii in https://github.com/PixelOS-AOSP/manifest/issues/17#issuecomment-2188714807_
            
![Screenshot 2024-06-25 171105](https://user-images.githubusercontent.com/107968141/342711518-388fa814-fe9b-49e4-b77d-bfe57f762f62.png)

Kindly Add -b thirteen to the repo packages_modules_connectivity  so that we can Initiate repo sync again

**Comment by hridaya2004** [comment]
As mentioned previously, we no longer maintain thirteen branches.

**Comment by hridaya2004** [comment]
Duplicate of https://github.com/PixelOS-AOSP/manifest/issues/12
