### ISSUE TITLE
Could not fetch platform/external/aac

### ISSUE THREAD

**Issue by wtfroichi** [PixelOS-Pixelish/manifest#20]
Whenever trying to _repo sync_ on Ubuntu 22.04, I'm getting errors at finding the _android-14.0.0_r73_ tag on _aac_ repo. This tag is actually into the _googlesource_ GIT project, there's no reason to fail (?). Also, even if I tried to get rid of this, _repo_ is **not** replacing all objects into their respective folders as it's supposed to due to the lack of _aac_, and I'm unable to build any new ROM since last update.

**Comment by wtfroichi** [comment]
Also tried to modify the manifest.xml file removing aac from there & placing it onto a new local manifest to sync _(repo init -u [...] -m custom.xml)_ but same thing, I've been having this for 3 weeks and no way of solving...

**Comment by wtfroichi** [comment]
I know this is _fourteen_ (no longer mantained) branch but, any known way to solve it?

**Comment by hridaya2004** [comment]
I am guessing you can manual sync the repository in that case, which should *work* just fine.

**Comment by wtfroichi** [comment]
Already tried also, but _repo_ gives an error as it isn't finding the tag on _aac.git_ source, so when replacing objects (alphabetical order, to /path/to/android_build_env-dir/) it's stopping at the point of finding the error on aac source...
