### ISSUE TITLE
GMS Build failed

### ISSUE THREAD

**Issue by WilliamSado** [PixelOS-Pixelish/manifest#7]
I build PixelOS time have this issue Guess is gms source issue
Error log: 
FAILED: out/soong/.intermediates/vendor/gms/common/AICorePrebuilt/android_common/zip-aligned/AICorePrebuilt.apk
if ! out/host/linux-x86/bin/zipalign -c -p 4 out/soong/.intermediates/vendor/gms/common/AICorePrebuilt/android_common/dex-uncompressed/AICorePrebuilt.apk > /dev/null; then out/host/linux-x86/bin/zipalign -f -p 4 out/soong/.intermediates/vendor/gms/common/AICorePrebuilt/android_common/dex-uncompressed/AICorePrebuilt.apk out/soong/.intermediates/vendor/gms/common/AICorePrebuilt/android_common/zip-aligned/AICorePrebuilt.apk; else cp -f out/soong/.intermediates/vendor/gms/common/AICorePrebuilt/android_common/dex-uncompressed/AICorePrebuilt.apk out/soong/.intermediates/vendor/gms/common/AICorePrebuilt/android_common/zip-aligned/AICorePrebuilt.apk; fi
Unable to open 'out/soong/.intermediates/vendor/gms/common/AICorePrebuilt/android_common/dex-uncompressed/AICorePrebuilt.apk' for verification
Unable to open 'out/soong/.intermediates/vendor/gms/common/AICorePrebuilt/android_common/dex-uncompressed/AICorePrebuilt.apk' as zip archive

**Comment by redducc** [comment]
> I build PixelOS time have this issue Guess is gms source issue Error log: FAILED: out/soong/.intermediates/vendor/gms/common/AICorePrebuilt/android_common/zip-aligned/AICorePrebuilt.apk if ! out/host/linux-x86/bin/zipalign -c -p 4 out/soong/.intermediates/vendor/gms/common/AICorePrebuilt/android_common/dex-uncompressed/AICorePrebuilt.apk > /dev/null; then out/host/linux-x86/bin/zipalign -f -p 4 out/soong/.intermediates/vendor/gms/common/AICorePrebuilt/android_common/dex-uncompressed/AICorePrebuilt.apk out/soong/.intermediates/vendor/gms/common/AICorePrebuilt/android_common/zip-aligned/AICorePrebuilt.apk; else cp -f out/soong/.intermediates/vendor/gms/common/AICorePrebuilt/android_common/dex-uncompressed/AICorePrebuilt.apk out/soong/.intermediates/vendor/gms/common/AICorePrebuilt/android_common/zip-aligned/AICorePrebuilt.apk; fi Unable to open 'out/soong/.intermediates/vendor/gms/common/AICorePrebuilt/android_common/dex-uncompressed/AICorePrebuilt.apk' for verification Unable to open 'out/soong/.intermediates/vendor/gms/common/AICorePrebuilt/android_common/dex-uncompressed/AICorePrebuilt.apk' as zip archive

cd vendor/gms
git lfs install
git lfs pull

**Comment by WilliamSado** [comment]
Thanks I will close this issue
